version: '3.9'
services:
  frontend:
    container_name: orbita-challenge-project
    build: ./orbita-project
    ports:
      - 8080:8080
    working_dir: /orbita-challenge-project
    volumes:
      - ./orbita-project/src:/orbita-project/src
    restart: 'always'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:8080']
      timeout: 10s
      retries: 5
